# Generated by Django 4.0 on 2021-12-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserloginForm',
        ),
        migrations.RenameField(
            model_name='usersignform',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='usersignform',
            old_name='repeat_password',
            new_name='repeat_Password',
        ),
    ]
